- name: tomcat-hosting
  hosts: all
  become: yes
  vars:
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
    tomcat_split_url: "{{tomcat_url.split('/') | last}}"
    tomcat_dir: "/opt/{{tomcat_split_url | }}"
  tasks:  
    - name: tomcat downloading
    
