- name: host template via ansible
  hosts: all
  become: yes
  tasks:
    - name: install httpd server
      package:
        name: httpd 
        state: present

    - name: start httpd server
      shell: systemctl start httpd

    - name: download CSS template 
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page287/onix-digital.zip
        dest: /mnt/.
    
    - name: removing exixting filr from /var/www/html/index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Unarchive CSS template /mnt/. /var/www/html/
      unarchive: 
        src: /mnt/onix-digital.zip 
        dest: /var/www/html/
        remote_src: yes



        

