- name: package installed
  hosts: all
  become: yes
  tasks:
    - name: install packages
      yum:
        name: 
           - vsftpd 
           - gzip2
           - rsync
           - tree
          
        state: present     
