- name: package installed
  hosts: all
  become: yes
  tasks:
    - name: install packages
      yum:
        name: 
           - httpd
           - mariadb
           - nfs-utils
           - tree
        state: present     
