- name: host tomcat server
  hosts: all
  become: yes
  vars: 
    download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.zip
  tasks:
    - name: remove tomcat server
      shell: "rm -rfv /opt/*"
    
    - name: download java 11   
      become: yes 
      shell: "amazon-linux-extras install java-openjdk11 -y"
        
    

    - name: download tomcat-9 using unarchive
      unarchive:  
        src: "{{download_url}}" 
        dest: /opt
        remote_src: yes
    - name: chmod
      shell: chmod +rx /opt/apache-tomcat-9.0.71/bin/catalina.sh

    - name: chmod
      shell: chmod +rx /opt/apache-tomcat-9.0.71/bin/startup.sh
    - name: catalina start tomcat-9
      command:  nohup /opt/apache-tomcat-9.0.71/bin/startup.sh
  
   
