- name: splitting examples
  hosts: all
  vars: 
   url: www.example.com
   
  var_files:
    - filevars.yml
  
  tasks:
    - name: variables print
      debug: 
       msg: "my variables is {{url}}"
