- name: host tomcat server
  hosts: all
  become: yes
  vars: 
    download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.zip
  tasks:
    - name: download java 11    
      shell: 
        - "amazon-linux-extras install java-openjdk11"
        - "java --version"
    - name: create tomcat-9 directory
      file: path=/opt/tomcat-9 state=directory
    - name: download tomcat-9 using unarchive
      unarchive:  src="{{download_url}}" dest="{{/opt/tomcat-9/}}"
      remote_src: yes
    - name: moving tomcat-9
      shell: "mv /opt/tomcat-9/apache*/* /opt/tomcat-9"
      

   
