- name: variable values
  hosts: all
  vars:
    url: www.global.com
  tasks:
    - name: task-1
      debug:
        msg: "the value of the variable is {{url}}"
      vars:
        url: www.mylocal.com
        var_files: filevars.yml
    - name: task-2
      debug: 
        msg: "the value of the variable is {{url}}"
      